name: refbot2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.0.1
  - python=3.10.17
  - python_abi=3.10
  - readline=8.2
  - setuptools=79.0.1
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.50.0
      - anyio==4.9.0
      - argcomplete==3.6.2
      - attrs==25.3.0
      - av==14.3.0
      - av2==0.3.4
      - beautifulsoup4==4.7.1
      - beautifultable==0.7.0
      - boto3==1.38.3
      - botocore==1.38.3
      - chardet==4.0.0
      - click==6.7
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.14
      - dependency-groups==1.3.0
      - dill==0.4.0
      - distlib==0.3.9
      - distro==1.9.0
      - docker==3.6.0
      - docker-pycreds==0.4.0
      - evalai==1.3.18
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - google-genai==1.12.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==2.10
      - imageio==2.37.0
      - ipykernel==6.29.5
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - llvmlite==0.44.0
      - lxml==4.6.2
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nox==2025.2.9
      - numba==0.61.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - pathos==0.3.4
      - pillow==11.2.1
      - platformdirs==4.3.7
      - polars==1.27.1
      - pooch==1.8.2
      - pox==0.3.6
      - ppft==1.7.7
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pycocotools==2.0.8
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - python-dateutil==2.7.3
      - pytz==2025.2
      - pyvista==0.45.0
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - requests==2.25.1
      - rich==14.0.0
      - s3transfer==0.12.0
      - safetensors==0.5.3
      - scipy==1.15.2
      - scooby==0.10.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==1.1.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - trackeval==1.0.dev1
      - transformers==4.51.3
      - triton==3.3.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - universal-pathlib==0.2.6
      - urllib3==1.26.20
      - validators==0.12.6
      - virtualenv==20.30.0
      - vtk==9.4.2
      - websocket-client==1.8.0
      - websockets==15.0.1
